const filesActionTypes = {
    SET_CATEGORY: 'SET_CATEGORY',

    UPLOAD_FILE: 'UPLOAD_FILE',
    UPLOAD_FILE_ERROR: 'UPLOAD_FILE_ERROR',
    UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',

    DELETE_FILE_START: 'DELETE_FILE_START',
    DELETE_FILE_SUCCESS: 'DELETE_FILE_SUCCESS',
    DELETE_FILE_FAILURE: 'DELETE_FILE_FAILURE',

    FETCH_FILES_START: 'FETCH_FILES_START',
    FETCH_FILES_SUCCESS: 'FETCH_FILES_SUCCESS',
    FETCH_FILES_FAILURE: 'FETCH_FILES_FAILURE',

    FILE_UPLOADING: 'FILE_UPLOADING'

}

export default filesActionTypes;