const musicActionTypes = {
    FETCH_MUSIC_START: 'FETCH_MUSIC_START',
    FETCH_MUSIC_SUCCESS: 'FETCH_MUSIC_SUCCESS',
    FETCH_MUSIC_FAILURE: 'FETCH_MUSIC_FAILURE',
    ADD_TO_PLAYLIST: 'ADD_TO_PLAYLIST',
    SET_SEARCH_ENTRY: 'SET_SEARCH_ENTRY'
}

export default musicActionTypes;